services:
  api:
    build: ./src/MentionSync.API
    environment:
      - ConnectionStrings__pg=Host=pg;Username=postgres;Password=postgres;Database=mentions
      - Slack__SigningSecret=changeme
      - Graph__AccessToken=changeme
      - Graph__NotificationUrl=http://host.docker.internal:8080/webhooks/msgraph
      - Smtp__Host=localhost
      - Smtp__Port=1025
      - Smtp__From=alerts@mentionsync.local
    ports:
      - "8080:8080"
    depends_on:
      - pg
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
